import Head from 'next/head'
import SarMainPageHeader from '../../components/sarMainPageHeader'
import SarMainPageFooter from '../../components/sarMainPageFooter'
import { useState } from 'react'
import { useRouter } from 'next/router'

function Sar() {
  const router = useRouter()
  const [serachTerm, setSearchTerm] = useState()
  const submitHandler = (e) => {
    e.preventDefault()

    router.push({
      pathname: '/sar/search',
      query: { search: serachTerm },
    })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" />
         <link
          href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100;200;300;500&display=swap"
          rel="stylesheet"
        ></link>  */}
      </Head>
      <SarMainPageHeader />
      <main id="main">
        <div className="container">
          <div className="main">
            <div className="main-inner-holder">
              <form onSubmit={submitHandler}>
                <div className="main-inner-holder-search">
                  <input
                    type="text"
                    onChange={(e) => setSearchTerm(e.target.value)}
                  />
                </div>

                <div className="main-inner-holder-button">
                  <button>بگرد</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </main>
      <SarMainPageFooter />
    </>
  )
}
export default Sar
