import Head from 'next/head'
import Image from 'next/image'
import SarHeader from '../../../components/sarHeader'

function Search({ searchTerm }) {
  const { result } = searchTerm
  console.log(searchTerm)
  let metaData
  // let metaData = [];
  //   result.map((res) => {
  //     metaData.push(JSON.parse(res.metadata));
  //   });
  //   console.log(metaData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Vazirmatn:wght@100;200;300;500&display=swap"
          rel="stylesheet"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        />
      </Head>
      <SarHeader />
      <div className="container">
        <div className="result-section">
          {
            //   metaData.map((searchItem) => {
            //     return (
            //       <div key={searchItem} className="result-single">
            //         {/* <Image
            //                 src={`${searchItem.metadata.image}`}
            //                 width={250}
            //                 height={250}
            //             /> */}
            //         <p>{searchItem.name}</p>
            //       </div>
            //     );
            //   })
            // result.map((searchItem) => {
            //   metaData = JSON.parse(searchItem.metadata)
            //   return (
            //     <div key={searchItem.token_id} className="result-single">
            //       {/* <Image
            //     //                 src={`${searchItem.metadata.image}`}
            //     //                 width={250}
            //     //                 height={250}
            //     //             /> */}
            //       <p>{metaData.name}</p>
            //     </div>
            //   )
            // })
          }
        </div>
      </div>
    </>
  )
}
export default Search

export async function getServerSideProps(context) {
  const params = context
  const searchTerm = params.query.search || 'NFT'
  const options = {
    method: 'GET',
    headers: {
      'X-RapidAPI-Key': '649ab10b91msh8326ab42db9ea91p1c2c4cjsn2a8e79c8bee7',
      'X-RapidAPI-Host': 'nft-explorer.p.rapidapi.com',
    },
  }

  const response = await fetch(
    `https://nft-explorer.p.rapidapi.com/search?chain=eth&filter=name&q=${searchTerm}`,
    options
  )
  const data = await response.json()

  return {
    props: {
      searchTerm: data,
    },
  }
}
